name: snake

on:
  schedule:
    - cron: "17 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths: [.github/workflows/snake.yml]

permissions:
  contents: write

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#7c3aed&color_dots=#ebedf0,#e9d5ff,#c084fc,#9333ea,#581c87
            dist/github-snake-dark.svg?color_snake=#e879f9&color_dots=#161b22,#3b0764,#6b21a8,#a855f7,#e9d5ff

      - uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: regenerate contribution snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
